In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os

PATH = os.getcwd()
for _ in range(2):
    PATH = os.path.dirname(PATH)
if PATH not in sys.path:
    sys.path.append(PATH)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from FactorAnalysis.week1.helpers.query_factors import (
    get_all_stocks,
    get_index_stocks,
    compute_factors_and_save
)
from FactorAnalysis.week1.helpers.data_processing import read_from_db, read_table_names

## Compute Factors for Selected Stocks

In [18]:
ts_codes = ["000001.SZ", "000002.SZ", "000004.SZ"]
db_in_filename = "data/stocks_raw_data.db"
db_out_filename = "data/factors_test.db"
log_dir = "../logging/"

all_factors = compute_factors_and_save(ts_codes, db_in_filename, db_out_filename, log_dir)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:05<00:00,  1.74s/it]

In [20]:
all_factors

                          total_mv       pe       pb  turnover_rate  \
trade_date ts_code
2018-01-02 000001.SZ  2.352346e+07  10.4091   1.1871         1.2304
           000002.SZ  3.594348e+07  17.0975   3.0886         0.7039
           000004.SZ  1.876039e+05  47.7372  16.2585         0.7548
2018-01-03 000001.SZ  2.288816e+07  10.1280   1.1550         1.7511
           000002.SZ  3.568958e+07  16.9768   3.0668         0.6662
...                            ...      ...      ...            ...
2023-12-28 000002.SZ  1.255111e+07   5.5492   0.4963         0.8128
           000004.SZ  2.088961e+05      NaN   6.5835         2.8255
2023-12-29 000001.SZ  1.822216e+07   4.0035   0.4603         0.4400
           000002.SZ  1.247952e+07   5.5176   0.4934         0.6320
           000004.SZ  2.135294e+05      NaN   6.7295         2.7268

                      reversal_rate  volatility   open   high    low  close  \
trade_date ts_code
2018-01-02 000001.SZ            NaN         NaN  13.35  13.93  13.32  13.70
           000002.SZ            NaN         NaN  31.45  32.99  31.45  32.56
           000004.SZ            NaN         NaN  22.29  22.49  22.00  22.34
2018-01-03 000001.SZ            NaN         NaN  13.73  13.86  13.20  13.33
           000002.SZ            NaN         NaN  32.50  33.78  32.23  32.33
...                             ...         ...    ...    ...    ...    ...
2023-12-28 000002.SZ       1.348748    1.835579  10.15  10.56  10.10  10.52
           000004.SZ      -1.313321    2.043528  15.68  15.89  15.43  15.78
2023-12-29 000001.SZ       2.176279    1.173004   9.42   9.48   9.35   9.39
           000002.SZ       1.553398    1.823013  10.48  10.59  10.39  10.46
           000004.SZ       2.673456    2.104420  15.73  16.23  15.72  16.13

                      ...  equity_yoy  gross_profit_margin  \
trade_date ts_code    ...
2018-01-02 000001.SZ  ...         NaN             0.285076
           000002.SZ  ...         NaN             0.210550
           000004.SZ  ...         NaN             0.070101
2018-01-03 000001.SZ  ...         NaN             0.285076
           000002.SZ  ...         NaN             0.210550
...                   ...         ...                  ...
2023-12-28 000002.SZ  ...      4.8945             0.098839
           000004.SZ  ...    -64.3841            -0.511857
2023-12-29 000001.SZ  ...      9.5152             0.383855
           000002.SZ  ...      4.8945             0.098839
           000004.SZ  ...    -64.3841            -0.511857

                      operating_profit_margin  net_profit_margin  \
trade_date ts_code
2018-01-02 000001.SZ                 0.285699           0.219207
           000002.SZ                 0.209195           0.153186
           000004.SZ                 0.063467           0.042511
2018-01-03 000001.SZ                 0.285699           0.219207
           000002.SZ                 0.209195           0.153186
...                                       ...                ...
2023-12-28 000002.SZ                 0.097181           0.072431
           000004.SZ                -0.511179          -0.447629
2023-12-29 000001.SZ                 0.384278           0.310536
           000002.SZ                 0.097181           0.072431
           000004.SZ                -0.511179          -0.447629

                      operating_cash_flow_to_net_income  \
trade_date ts_code
2018-01-02 000001.SZ                          -5.122256
           000002.SZ                           2.212481
           000004.SZ                           2.450593
2018-01-03 000001.SZ                          -5.122256
           000002.SZ                           2.212481
...                                                 ...
2023-12-28 000002.SZ                           0.011191
           000004.SZ                           1.092715
2023-12-29 000001.SZ                           2.924940
           000002.SZ                           0.011191
           000004.SZ                           1.092715

                      operating_cash_flow_to_revenue  current_ratio  \
trade_date ts_code
2018-01-02 000001.SZ                       -1.122833            NaN
           000002.SZ                        0.338921       1.200857
           000004.SZ                        0.104177       2.068985
2018-01-03 000001.SZ                       -1.122833            NaN
           000002.SZ                        0.338921       1.200857
...                                              ...            ...
2023-12-28 000002.SZ                        0.000811       1.371164
           000004.SZ                       -0.489131       2.408494
2023-12-29 000001.SZ                        0.908300            NaN
           000002.SZ                        0.000811       1.371164
           000004.SZ                       -0.489131       2.408494

                      cash_current_liability_ratio  cash_liability_ratio  \
trade_date ts_code
2018-01-02 000001.SZ                           NaN             -0.039248
           000002.SZ                      0.097153              0.084117
           000004.SZ                      0.205426              0.170373
2018-01-03 000001.SZ                           NaN             -0.039248
           000002.SZ                      0.097153              0.084117
...                                            ...                   ...
2023-12-28 000002.SZ                      0.000250              0.000190
           000004.SZ                     -0.221576             -0.213772
2023-12-29 000001.SZ                           NaN              0.022954
           000002.SZ                      0.000250              0.000190
           000004.SZ                     -0.221576             -0.213772

                      long_term_liability_operating_cash_flow_ratio
trade_date ts_code
2018-01-02 000001.SZ                                            NaN
           000002.SZ                                       1.166493
           000004.SZ                                            NaN
2018-01-03 000001.SZ                                            NaN
           000002.SZ                                       1.166493
...                                                             ...
2023-12-28 000002.SZ                                     913.897419
           000004.SZ                                            NaN
2023-12-29 000001.SZ                                            NaN
           000002.SZ                                     913.897419
           000004.SZ                                            NaN

[4343 rows x 25 columns]

In [19]:
all_factors.loc[(pd.to_datetime("20180102"),)]

,total_mv,pe,pb,turnover_rate,reversal_rate,volatility,open,high,low,close,...,equity_yoy,gross_profit_margin,operating_profit_margin,net_profit_margin,operating_cash_flow_to_net_income,operating_cash_flow_to_revenue,current_ratio,cash_current_liability_ratio,cash_liability_ratio,long_term_liability_operating_cash_flow_ratio
ts_code,,,,,,,,,,,,,,,,,,,,,
000001.SZ,2.352346e+07,10.4091,1.1871,1.2304,NaN,NaN,13.35,13.93,13.32,13.70,...,NaN,0.285076,0.285699,0.219207,-5.122256,-1.122833,NaN,NaN,-0.039248,NaN
000002.SZ,3.594348e+07,17.0975,3.0886,0.7039,NaN,NaN,31.45,32.99,31.45,32.56,...,NaN,0.210550,0.209195,0.153186,2.212481,0.338921,1.200857,0.097153,0.084117,1.166493
000004.SZ,1.876039e+05,47.7372,16.2585,0.7548,NaN,NaN,22.29,22.49,22.00,22.34,...,NaN,0.070101,0.063467,0.042511,2.450593,0.104177,2.068985,0.205426,0.170373,NaN

## Compute Factors for HS300 and ZZ500

In [4]:
table_names = read_table_names("data/stocks.db")
table_names

[('A_share',),
 ('HS300',),
 ('ZZ500',),
 ('index_info_399300.SZ',),
 ('index_info_399300_SZ',),
 ('index_info_000905_SH',)]

In [9]:
hs300 = get_index_stocks("399300.SZ", "data/stocks.db")
hs300.shape

(526,)

In [11]:
zz500 = get_index_stocks("000905.SH", "data/stocks.db")
zz500.shape

(1009,)

In [16]:
ts_codes = hs300.tolist() + zz500.tolist()
db_in_filename = "data/stocks_raw_data.db"
db_out_filename = "data/factors.db"
log_dir = "../logging/"

all_factors = compute_factors_and_save(ts_codes, db_in_filename, db_out_filename, log_dir)

In [20]:
# all_factors

In [11]:
all_factors_reloaded = read_from_db("factors_all_stocks", "data/factors.db", False, False)
all_factors_reloaded["trade_date"] = pd.to_datetime(all_factors_reloaded["trade_date"])
all_factors_reloaded = all_factors_reloaded.set_index(["trade_date", "ts_code"])
all_factors_reloaded

                          total_mv       pe      pb  turnover_rate  \
trade_date ts_code
2018-01-02 000001.SZ  2.352346e+07  10.4091  1.1871         1.2304
           000002.SZ  3.594348e+07  17.0975  3.0886         0.7039
           000008.SZ  2.471675e+06  47.3622  3.9588         0.4122
           000008.SZ  2.471675e+06  47.3622  3.9588         0.4122
           000009.SZ  1.573321e+06  67.4134  3.3833         0.9089
...                            ...      ...     ...            ...
2023-12-29 688777.SH  3.564168e+06  44.6677  3.7781         1.0662
           688778.SH  1.667936e+06  14.8850  1.9711         1.3076
           688779.SH  1.408329e+06   9.4551  1.8959         1.4990
           688819.SH  2.714103e+06  14.2235  1.8325         2.0174
           688981.SH  4.213257e+07  34.7254  2.9461         0.6409

                      reversal_rate  volatility   open   high    low  close  \
trade_date ts_code
2018-01-02 000001.SZ            NaN         NaN  13.35  13.93  13.32  13.70
           000002.SZ            NaN         NaN  31.45  32.99  31.45  32.56
           000008.SZ            NaN         NaN   8.75   8.82   8.70   8.77
           000008.SZ            NaN         NaN   8.75   8.82   8.70   8.77
           000009.SZ            NaN         NaN   7.27   7.33   7.23   7.32
...                             ...         ...    ...    ...    ...    ...
2023-12-29 688777.SH       0.331858    2.291518  45.30  45.72  45.05  45.35
           688778.SH       2.033462    1.749618  40.64  40.82  39.50  39.64
           688779.SH       3.253182    1.945117   7.35   7.41   7.28   7.30
           688819.SH       1.232777    1.552743  28.00  28.25  27.83  27.92
           688981.SH       0.018864    1.336868  53.00  53.50  52.88  53.02

                      ...  equity_yoy  gross_profit_margin  \
trade_date ts_code    ...
2018-01-02 000001.SZ  ...         NaN             0.285076
           000002.SZ  ...         NaN             0.210550
           000008.SZ  ...         NaN             0.437204
           000008.SZ  ...         NaN             0.437204
           000009.SZ  ...         NaN             0.054029
...                   ...         ...                  ...
2023-12-29 688777.SH  ...     93.2553             0.132342
           688778.SH  ...      6.3396             0.034162
           688779.SH  ...      4.3134             0.009363
           688819.SH  ...     12.8391             0.057639
           688981.SH  ...      7.6862             0.156187

                      operating_profit_margin  net_profit_margin  \
trade_date ts_code
2018-01-02 000001.SZ                 0.285699           0.219207
           000002.SZ                 0.209195           0.153186
           000008.SZ                 0.437721           0.381654
           000008.SZ                 0.437721           0.381654
           000009.SZ                 0.050868           0.046024
...                                       ...                ...
2023-12-29 688777.SH                 0.132386           0.124125
           688778.SH                 0.034347           0.031492
           688779.SH                 0.008315           0.008635
           688819.SH                 0.057333           0.046742
           688981.SH                 0.156065           0.145061

                      operating_cash_flow_to_net_income  \
trade_date ts_code
2018-01-02 000001.SZ                          -5.122256
           000002.SZ                           2.212481
           000008.SZ                          -0.059531
           000008.SZ                          -0.059531
           000009.SZ                           1.209313
...                                                 ...
2023-12-29 688777.SH                          -1.060379
           688778.SH                           3.626269
           688779.SH                         -37.973931
           688819.SH                           1.868812
           688981.SH                           3.404846

                      operating_cash_flow_to_revenue  current_ratio  \
trade_date ts_code
2018-01-02 000001.SZ                       -1.122833            NaN
           000002.SZ                        0.338921       1.200857
           000008.SZ                       -0.022720       1.890285
           000008.SZ                       -0.022720       1.890285
           000009.SZ                        0.055657       1.641650
...                                              ...            ...
2023-12-29 688777.SH                       -0.131619       2.009543
           688778.SH                        0.114197       2.191296
           688779.SH                       -0.327906       2.783655
           688819.SH                        0.087353       1.229520
           688981.SH                        0.493909       1.785040

                      cash_current_liability_ratio  cash_liability_ratio  \
trade_date ts_code
2018-01-02 000001.SZ                           NaN             -0.039248
           000002.SZ                      0.097153              0.084117
           000008.SZ                     -0.015444             -0.015169
           000008.SZ                     -0.015444             -0.015169
           000009.SZ                      0.035231              0.022775
...                                            ...                   ...
2023-12-29 688777.SH                     -0.095317             -0.090808
           688778.SH                      0.384741              0.289940
           688779.SH                     -0.731358             -0.359539
           688819.SH                      0.135340              0.120999
           688981.SH                      0.276265              0.140804

                      long_term_liability_operating_cash_flow_ratio
trade_date ts_code
2018-01-02 000001.SZ                                            NaN
           000002.SZ                                       1.166493
           000008.SZ                                            NaN
           000008.SZ                                            NaN
           000009.SZ                                       2.494184
...                                                             ...
2023-12-29 688777.SH                                      -0.401647
           688778.SH                                       0.736597
           688779.SH                                      -0.217856
           688819.SH                                       0.424436
           688981.SH                                       2.949345

[2031838 rows x 25 columns]

In [16]:
all_factors_reloaded.loc[("20190102",)].shape

(1302, 25)