In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os

PATH = os.getcwd()
for _ in range(2):
    PATH = os.path.dirname(PATH)
if PATH not in sys.path:
    sys.path.append(PATH)

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from FactorAnalysis.week1.helpers.query_factors import (
    get_all_stocks,
    compute_factors_and_save
)
from FactorAnalysis.week1.helpers.data_processing import read_from_db

## Compute Factors for Selected Stocks

In [18]:
ts_codes = ["000001.SZ", "000002.SZ", "000004.SZ"]
db_in_filename = "data/stocks_raw_data.db"
db_out_filename = "data/factors_test.db"
log_dir = "../logging/"

all_factors = compute_factors_and_save(ts_codes, db_in_filename, db_out_filename, log_dir)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:05<00:00,  1.74s/it]

In [20]:
all_factors

                          total_mv       pe       pb  turnover_rate  \
trade_date ts_code
2018-01-02 000001.SZ  2.352346e+07  10.4091   1.1871         1.2304
           000002.SZ  3.594348e+07  17.0975   3.0886         0.7039
           000004.SZ  1.876039e+05  47.7372  16.2585         0.7548
2018-01-03 000001.SZ  2.288816e+07  10.1280   1.1550         1.7511
           000002.SZ  3.568958e+07  16.9768   3.0668         0.6662
...                            ...      ...      ...            ...
2023-12-28 000002.SZ  1.255111e+07   5.5492   0.4963         0.8128
           000004.SZ  2.088961e+05      NaN   6.5835         2.8255
2023-12-29 000001.SZ  1.822216e+07   4.0035   0.4603         0.4400
           000002.SZ  1.247952e+07   5.5176   0.4934         0.6320
           000004.SZ  2.135294e+05      NaN   6.7295         2.7268

                      reversal_rate  volatility   open   high    low  close  \
trade_date ts_code
2018-01-02 000001.SZ            NaN         NaN  13.35  13.93  13.32  13.70
           000002.SZ            NaN         NaN  31.45  32.99  31.45  32.56
           000004.SZ            NaN         NaN  22.29  22.49  22.00  22.34
2018-01-03 000001.SZ            NaN         NaN  13.73  13.86  13.20  13.33
           000002.SZ            NaN         NaN  32.50  33.78  32.23  32.33
...                             ...         ...    ...    ...    ...    ...
2023-12-28 000002.SZ       1.348748    1.835579  10.15  10.56  10.10  10.52
           000004.SZ      -1.313321    2.043528  15.68  15.89  15.43  15.78
2023-12-29 000001.SZ       2.176279    1.173004   9.42   9.48   9.35   9.39
           000002.SZ       1.553398    1.823013  10.48  10.59  10.39  10.46
           000004.SZ       2.673456    2.104420  15.73  16.23  15.72  16.13

                      ...  equity_yoy  gross_profit_margin  \
trade_date ts_code    ...
2018-01-02 000001.SZ  ...         NaN             0.285076
           000002.SZ  ...         NaN             0.210550
           000004.SZ  ...         NaN             0.070101
2018-01-03 000001.SZ  ...         NaN             0.285076
           000002.SZ  ...         NaN             0.210550
...                   ...         ...                  ...
2023-12-28 000002.SZ  ...      4.8945             0.098839
           000004.SZ  ...    -64.3841            -0.511857
2023-12-29 000001.SZ  ...      9.5152             0.383855
           000002.SZ  ...      4.8945             0.098839
           000004.SZ  ...    -64.3841            -0.511857

                      operating_profit_margin  net_profit_margin  \
trade_date ts_code
2018-01-02 000001.SZ                 0.285699           0.219207
           000002.SZ                 0.209195           0.153186
           000004.SZ                 0.063467           0.042511
2018-01-03 000001.SZ                 0.285699           0.219207
           000002.SZ                 0.209195           0.153186
...                                       ...                ...
2023-12-28 000002.SZ                 0.097181           0.072431
           000004.SZ                -0.511179          -0.447629
2023-12-29 000001.SZ                 0.384278           0.310536
           000002.SZ                 0.097181           0.072431
           000004.SZ                -0.511179          -0.447629

                      operating_cash_flow_to_net_income  \
trade_date ts_code
2018-01-02 000001.SZ                          -5.122256
           000002.SZ                           2.212481
           000004.SZ                           2.450593
2018-01-03 000001.SZ                          -5.122256
           000002.SZ                           2.212481
...                                                 ...
2023-12-28 000002.SZ                           0.011191
           000004.SZ                           1.092715
2023-12-29 000001.SZ                           2.924940
           000002.SZ                           0.011191
           000004.SZ                           1.092715

                      operating_cash_flow_to_revenue  current_ratio  \
trade_date ts_code
2018-01-02 000001.SZ                       -1.122833            NaN
           000002.SZ                        0.338921       1.200857
           000004.SZ                        0.104177       2.068985
2018-01-03 000001.SZ                       -1.122833            NaN
           000002.SZ                        0.338921       1.200857
...                                              ...            ...
2023-12-28 000002.SZ                        0.000811       1.371164
           000004.SZ                       -0.489131       2.408494
2023-12-29 000001.SZ                        0.908300            NaN
           000002.SZ                        0.000811       1.371164
           000004.SZ                       -0.489131       2.408494

                      cash_current_liability_ratio  cash_liability_ratio  \
trade_date ts_code
2018-01-02 000001.SZ                           NaN             -0.039248
           000002.SZ                      0.097153              0.084117
           000004.SZ                      0.205426              0.170373
2018-01-03 000001.SZ                           NaN             -0.039248
           000002.SZ                      0.097153              0.084117
...                                            ...                   ...
2023-12-28 000002.SZ                      0.000250              0.000190
           000004.SZ                     -0.221576             -0.213772
2023-12-29 000001.SZ                           NaN              0.022954
           000002.SZ                      0.000250              0.000190
           000004.SZ                     -0.221576             -0.213772

                      long_term_liability_operating_cash_flow_ratio
trade_date ts_code
2018-01-02 000001.SZ                                            NaN
           000002.SZ                                       1.166493
           000004.SZ                                            NaN
2018-01-03 000001.SZ                                            NaN
           000002.SZ                                       1.166493
...                                                             ...
2023-12-28 000002.SZ                                     913.897419
           000004.SZ                                            NaN
2023-12-29 000001.SZ                                            NaN
           000002.SZ                                     913.897419
           000004.SZ                                            NaN

[4343 rows x 25 columns]

In [19]:
all_factors.loc[(pd.to_datetime("20180102"),)]

,total_mv,pe,pb,turnover_rate,reversal_rate,volatility,open,high,low,close,...,equity_yoy,gross_profit_margin,operating_profit_margin,net_profit_margin,operating_cash_flow_to_net_income,operating_cash_flow_to_revenue,current_ratio,cash_current_liability_ratio,cash_liability_ratio,long_term_liability_operating_cash_flow_ratio
ts_code,,,,,,,,,,,,,,,,,,,,,
000001.SZ,2.352346e+07,10.4091,1.1871,1.2304,NaN,NaN,13.35,13.93,13.32,13.70,...,NaN,0.285076,0.285699,0.219207,-5.122256,-1.122833,NaN,NaN,-0.039248,NaN
000002.SZ,3.594348e+07,17.0975,3.0886,0.7039,NaN,NaN,31.45,32.99,31.45,32.56,...,NaN,0.210550,0.209195,0.153186,2.212481,0.338921,1.200857,0.097153,0.084117,1.166493
000004.SZ,1.876039e+05,47.7372,16.2585,0.7548,NaN,NaN,22.29,22.49,22.00,22.34,...,NaN,0.070101,0.063467,0.042511,2.450593,0.104177,2.068985,0.205426,0.170373,NaN